### ISSUE TITLE
sporadic websocket parse errors (unexpected token)

### ISSUE THREAD

**Issue by kopierschnitte** [TA2k/ioBroker.gruenbeck#54]
Hi!

Ich bekommen ein paar Mal am Tag folgende Meldungen:

`<html>
<body>

gruenbeck.0 | 2023-05-14 08:24:30.352 | error | {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS5005xxxx","type":"Current","ibuiltindev":true,"isncu":"2022yyyyy","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":77,"mresidcap2":59,"mrescapa1":1.051,"mrescapa2":0.8,"mmaint":350,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}{"type":6}
-- | -- | -- | --
gruenbeck.0 | 2023-05-14 08:24:30.352 | error | SyntaxError: Unexpected token { in JSON at position 416
gruenbeck.0 | 2023-05-14 08:24:30.352 | error | Websocket parse error

</body>
</html>`

Verstehe aber nicht, wo das Problem ist. An Position 416 ist meiner Rechnung nach ein **}** und kein **{** zum Abschluss des Datensatzes. Der JSON-String an sich ist auch syntaktisch völlig ok...

**Comment by TA2k** [comment]
da sind zwei nachrichten aneinander probier mal die github version ob die damit umgehen kann

**Comment by kopierschnitte** [comment]
Hmm, jetzt klappt's gar nicht mehr. Direkt nach Adapterstart kommt wiederholt:

<html>
<body>


gruenbeck.0 | 2023-05-14 09:54:13.402 | info | Websocket closed
-- | -- | -- | --
gruenbeck.0 | 2023-05-14 09:54:13.402 | info | 1000
gruenbeck.0 | 2023-05-14 09:54:13.356 | error | {"type":6}
gruenbeck.0 | 2023-05-14 09:54:13.356 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-14 09:54:13.354 | error | Websocket parse error


</body>
</html>

**Comment by kopierschnitte** [comment]
Sorry. Hier der Ausschnitt im Debug-Log:

<html>
<body>


gruenbeck.0 | 2023-05-14 10:01:51.413 | info | Websocket closed
-- | -- | -- | --
gruenbeck.0 | 2023-05-14 10:01:51.413 | info | 1000
gruenbeck.0 | 2023-05-14 10:01:51.364 | error | {"type":6}
gruenbeck.0 | 2023-05-14 10:01:51.363 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-14 10:01:51.363 | error | Websocket parse error
gruenbeck.0 | 2023-05-14 10:01:51.362 | debug | {"type":6}
gruenbeck.0 | 2023-05-14 10:01:50.703 | debug | {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxxx","type":"Current","ibuiltindev":true,"isncu":"yyyy","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.025,"mrescapa2":0.8,"mmaint":350,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-14 10:01:50.517 | debug | ""
gruenbeck.0 | 2023-05-14 10:01:50.516 | debug | refreshSD response:
gruenbeck.0 | 2023-05-14 10:01:50.500 | debug | {"type":1,"target":"SendOneTimeMessageToDevice","arguments":[{"id":"xxxx","type":"CurrSlow","ibuiltindev":true,"isncu":"yyyy","mcountreg":9,"mcountwater1":5732,"mcountwater2":0,"mcountwatertank":14,"msaltusage":5.5136,"mflowexc":0,"mflowexc2reg1":0,"mflowexc1reg2":0,"mlifeadsorb":0,"mhardsoftw":5,"mcapacity":20,"maverage":99,"mstddev":0,"mmax":0,"mpress":0,"mtemp":0,"mflowmax":1.83,"mflowmax1reg2":0,"mflowmax2reg1":0,"mendreg1":"07:00","mendreg2":"00:00"}]}
gruenbeck.0 | 2023-05-14 10:01:50.407 | debug | {}
gruenbeck.0 | 2023-05-14 10:01:50.361 | debug | WS connected
gruenbeck.0 | 2023-05-14 10:01:50.252 | debug | refreshSD


</body>
</html>

**Comment by TA2k** [comment]
nochmal installieren habe was angepasst

**Comment by kopierschnitte** [comment]
Super, danke!
Auf den ersten Blick keine Probleme mehr.
Würde aber gerne noch 24h beobachten...

**Comment by kopierschnitte** [comment]
Leider ist der ursprüngliche Fehler wieder zurück:
<html>
<body>


gruenbeck.0 | 2023-05-14 12:46:03.881 | error | {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxxx","type":"Current","ibuiltindev":true,"isncu":"yyy","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":73,"mresidcap2":59,"mrescapa1":0.988,"mrescapa2":0.8,"mmaint":350,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}{"type":6}
-- | -- | -- | --
gruenbeck.0 | 2023-05-14 12:46:03.881 | error | SyntaxError: Unexpected token { in JSON at position 416
gruenbeck.0 | 2023-05-14 12:46:03.879 | error | Websocket parse error


</body>
</html>

Es ist auch definitiv die aktuelle Github-Version installiert (habe ich anhand von Zeile 738 in der main.js überprüft).

**Comment by TA2k** [comment]
Bitte nochmal

**Comment by kopierschnitte** [comment]
Okay, die Aussetzer sind jetzt seltener, dafür "heftiger":

<html>
<body>


host.iobroker | 2023-05-15 10:58:28.039 | error | instance system.adapter.gruenbeck.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:84:10)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:158:22)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:459:17)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver.dataMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:541:14)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver.emit (node:domain:489:12)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver.emit (node:events:513:28)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1184:20)
host.iobroker | 2023-05-15 10:58:28.038 | error | Caught by controller[0]: at WebSocket.emit (node:domain:489:12)
host.iobroker | 2023-05-15 10:58:28.037 | error | Caught by controller[0]: at WebSocket.emit (node:events:513:28)
host.iobroker | 2023-05-15 10:58:28.037 | error | Caught by controller[0]: at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.gruenbeck/main.js:770:38)
host.iobroker | 2023-05-15 10:58:28.035 | error | Caught by controller[0]: ReferenceError: dataCleaned is not defined
gruenbeck.0 | 2023-05-15 10:58:27.435 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
gruenbeck.0 | 2023-05-15 10:58:27.434 | info | terminating
gruenbeck.0 | 2023-05-15 10:58:27.390 | error | dataCleaned is not defined
gruenbeck.0 | 2023-05-15 10:58:27.390 | error | ReferenceError: dataCleaned is not defined at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.gruenbeck/main.js:770:38) at WebSocket.emit (node:events:513:28) at WebSocket.emit (node:domain:489:12) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1184:20) at Receiver.emit (node:events:513:28) at Receiver.emit (node:domain:489:12) at Receiver.dataMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:541:14) at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:459:17) at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:158:22) at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:84:10)
gruenbeck.0 | 2023-05-15 10:58:27.389 | error | uncaught exception: dataCleaned is not defined
gruenbeck.0 | 2023-05-15 10:58:27.371 | error | {"type":6}{"type":1,"target":"SendMessageToDevice","arguments":[{"id":"yyyy","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":54,"mresidcap2":59,"mrescapa1":0.738,"mrescapa2":0.8,"mmaint":349,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-15 10:58:27.370 | error | SyntaxError: Unexpected token { in JSON at position 10
gruenbeck.0 | 2023-05-15 10:58:27.365 | error | Websocket parse error


</body>
</html>
Der obige Fehler kam nicht direkt nach dem Adapterstart sondern einige Stunden später.
Jedoch startet der Adapter danach klaglos selber neu und läuft auch jetzt schon einen halben Tag durch.

**Comment by kopierschnitte** [comment]
Seit dem letzten Commit (https://github.com/TA2k/ioBroker.gruenbeck/commit/695f8d82c1d2d9a3b2fd918f411038112f38ca84) läuft es ohne Probleme.

Vielen Dank!

**Comment by kopierschnitte** [comment]
Leider zu früh gefreut:

<html>
<body>


gruenbeck.0 | 2023-05-18 10:46:51.282 | info | Websocket closed
-- | -- | -- | --
gruenbeck.0 | 2023-05-18 10:46:51.282 | info | 1000
gruenbeck.0 | 2023-05-18 10:46:51.220 | error | {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxxx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":73,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":96,"mresidcap2":59,"mrescapa1":1.305,"mrescapa2":0.8,"mmaint":346,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}{"type":6}
gruenbeck.0 | 2023-05-18 10:46:51.220 | error | {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxxx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":73,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":96,"mresidcap2":59,"mrescapa1":1.305,"mrescapa2":0.8,"mmaint":346,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}{"type":6}
gruenbeck.0 | 2023-05-18 10:46:51.219 | error | SyntaxError: Unexpected token { in JSON at position 415


</body>
</html>

**Comment by TA2k** [comment]
Nochmal probieren

**Comment by kopierschnitte** [comment]
Nope, leider nicht. Ist aber auch wirklich ein nerviges Trennzeichen:

<html>
<body>


gruenbeck.0 | 2023-05-19 09:08:54.941 | info | Websocket closed
-- | -- | -- | --
gruenbeck.0 | 2023-05-19 09:08:54.941 | info | 1000
gruenbeck.0 | 2023-05-19 09:08:54.888 | error | {"type":6}{"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxxx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":96,"mresidcap2":59,"mrescapa1":1.303,"mrescapa2":0.8,"mmaint":345,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-19 09:08:54.887 | error | {"type":6}{"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxxx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":96,"mresidcap2":59,"mrescapa1":1.303,"mrescapa2":0.8,"mmaint":345,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-19 09:08:54.887 | error | SyntaxError: Unexpected token { in JSON at position 10
gruenbeck.0 | 2023-05-19 09:08:54.886 | error | Websocket parse error


</body>
</html>

**Comment by TA2k** [comment]
nochmal

**Comment by kopierschnitte** [comment]
Jetzt bricht er gleich beim Start ab:

<html>
<body>


gruenbeck.0 | 2023-05-19 11:35:28.911 | info | Websocket closed
-- | -- | -- | --
gruenbeck.0 | 2023-05-19 11:35:28.906 | info | 1000
gruenbeck.0 | 2023-05-19 11:35:28.883 | error | {"type":6}
gruenbeck.0 | 2023-05-19 11:35:28.883 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-19 11:35:28.882 | error | Websocket parse error
gruenbeck.0 | 2023-05-19 11:35:28.847 | error | {}
gruenbeck.0 | 2023-05-19 11:35:28.846 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-19 11:35:28.844 | error | Websocket parse error
gruenbeck.0 | 2023-05-19 11:35:23.464 | info | Websocket closed
gruenbeck.0 | 2023-05-19 11:35:23.464 | info | 1000
gruenbeck.0 | 2023-05-19 11:35:23.415 | error | {}
gruenbeck.0 | 2023-05-19 11:35:23.414 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-19 11:35:23.413 | error | Websocket parse error
gruenbeck.0 | 2023-05-19 11:35:22.882 | info | Using device softliQ.D/xx
gruenbeck.0 | 2023-05-19 11:35:22.882 | info | Filtered to 1 devices
gruenbeck.0 | 2023-05-19 11:35:22.881 | info | Found 1 devices
gruenbeck.0 | 2023-05-19 11:35:22.610 | info | Login successful
gruenbeck.0 | 2023-05-19 11:35:22.036 | info | Login step 2
gruenbeck.0 | 2023-05-19 11:35:21.340 | info | Login step 1
gruenbeck.0 | 2023-05-19 11:35:20.896 | info | Connection to SD Device with:xx@yy.de
gruenbeck.0 | 2023-05-19 11:35:20.845 | info | starting. Version 0.0.42 (non-npm: TA2k/ioBroker.gruenbeck#117dccb40f3e2c2b2598c9578193e6c0ce4f7b15) in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v16.19.1, js-controller: 4.0.24


</body>
</html>

**Comment by TA2k** [comment]
ich habe nochmal logs hinzugefügt

**Comment by kopierschnitte** [comment]
Gerne:

<html>
<body>


gruenbeck.0 | 2023-05-19 22:13:09.190 | info | Websocket closed
-- | -- | -- | --
gruenbeck.0 | 2023-05-19 22:13:09.190 | info | 1000
gruenbeck.0 | 2023-05-19 22:13:09.152 | error | {}
gruenbeck.0 | 2023-05-19 22:13:09.152 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-19 22:13:09.152 | error | Websocket parse error
gruenbeck.0 | 2023-05-19 22:13:09.152 | info | element:
gruenbeck.0 | 2023-05-19 22:13:09.152 | info | element: {}
gruenbeck.0 | 2023-05-19 22:13:09.151 | info | ["{}",""]
gruenbeck.0 | 2023-05-19 22:13:03.776 | info | Websocket closed
gruenbeck.0 | 2023-05-19 22:13:03.776 | info | 1000
gruenbeck.0 | 2023-05-19 22:13:03.720 | error | {}
gruenbeck.0 | 2023-05-19 22:13:03.719 | error | SyntaxError: Unexpected end of JSON input
gruenbeck.0 | 2023-05-19 22:13:03.715 | error | Websocket parse error
gruenbeck.0 | 2023-05-19 22:13:03.714 | info | element:
gruenbeck.0 | 2023-05-19 22:13:03.714 | info | element: {}
gruenbeck.0 | 2023-05-19 22:13:03.713 | info | ["{}",""]
gruenbeck.0 | 2023-05-19 22:13:03.128 | info | Using device softliQ.D/xxxx
gruenbeck.0 | 2023-05-19 22:13:03.128 | info | Filtered to 1 devices
gruenbeck.0 | 2023-05-19 22:13:03.128 | info | Found 1 devices
gruenbeck.0 | 2023-05-19 22:13:02.875 | info | Login successful
gruenbeck.0 | 2023-05-19 22:13:02.189 | info | Login step 2
gruenbeck.0 | 2023-05-19 22:13:01.780 | info | Login step 1
gruenbeck.0 | 2023-05-19 22:13:01.388 | info | Connection to SD Device with:xx@yy.de
gruenbeck.0 | 2023-05-19 22:13:01.339 | info | starting. Version 0.0.42 (non-npm: TA2k/ioBroker.gruenbeck#048861b98b805c8c26e87907ec48cc884c48dc28) in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v16.19.1, js-controller: 4.0.24


</body>
</html>

**Comment by TA2k** [comment]
jetzt könnte es funktionieren

**Comment by kopierschnitte** [comment]
In der Tat! Es sieht auch direkt gut aus. Nachrichten werden wohl korrekt aufgeteilt:

<html>
<body>


gruenbeck.0 | 2023-05-20 12:12:55.255 | info | element: {"type":6}
-- | -- | -- | --
gruenbeck.0 | 2023-05-20 12:12:54.828 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxx","type":"Current","ibuiltindev":true,"isncu":"xxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:53.734 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:52.689 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:51.692 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xx","type":"Current","ibuiltindev":true,"isncu":"xxxx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:50.563 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:49.660 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:49.257 | info | element: {"type":6}
gruenbeck.0 | 2023-05-20 12:12:48.517 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:47.522 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:46.324 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:45.440 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:44.257 | info | element: {"type":6}
gruenbeck.0 | 2023-05-20 12:12:44.249 | info | element: {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"xxx","type":"Current","ibuiltindev":true,"isncu":"xx","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregstatus":0,"mresidcap1":75,"mresidcap2":59,"mrescapa1":1.02,"mrescapa2":0.8,"mmaint":344,"mflow1":0,"mflow2":0,"mflowreg1":0,"mflowreg2":0,"mflowblend":0,"mstep1":4950,"mstep2":0,"mcurrent":0,"mreswatadmod":0,"msaltrange":99}]}
gruenbeck.0 | 2023-05-20 12:12:43.990 | info | element: {"type":1,"target":"SendOneTimeMessageToDevice","arguments":[{"id":"xxx","type":"CurrSlow","ibuiltindev":true,"isncu":"xx","mcountreg":12,"mcountwater1":8450,"mcountwater2":0,"mcountwatertank":20,"msaltusage":7.5518,"mflowexc":0,"mflowexc2reg1":0,"mflowexc1reg2":0,"mlifeadsorb":0,"mhardsoftw":5,"mcapacity":20,"maverage":99,"mstddev":0,"mmax":1,"mpress":0,"mtemp":0,"mflowmax":1.83,"mflowmax1reg2":0,"mflowmax2reg1":0,"mendreg1":"07:04","mendreg2":"00:00"}]}
gruenbeck.0 | 2023-05-20 12:12:43.794 | info | element: {}
gruenbeck.0 | 2023-05-20 12:12:43.230 | info | Using device softliQ.D/xxx
gruenbeck.0 | 2023-05-20 12:12:43.229 | info | Filtered to 1 devices
gruenbeck.0 | 2023-05-20 12:12:43.228 | info | Found 1 devices
gruenbeck.0 | 2023-05-20 12:12:43.033 | info | Login successful
gruenbeck.0 | 2023-05-20 12:12:42.507 | info | Login step 2
gruenbeck.0 | 2023-05-20 12:12:41.999 | info | Login step 1
gruenbeck.0 | 2023-05-20 12:12:41.579 | info | Connection to SD Device with:xx@xx.de
gruenbeck.0 | 2023-05-20 12:12:41.518 | info | starting. Version 0.0.42 (non-npm: TA2k/ioBroker.gruenbeck#e31ad056b79c77cd3aa010fc5147e130285cee31) in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v16.19.1, js-controller: 4.0.24


</body>
</html>

Das wiederholt sich dann ganz brav. Manchmal kommen auch mehrere Type 6 nacheinander. Wird aber auch korrekt abgefangen.

Werde beobachten. Danke!
